#ifndef ALIEN_LEXER_STUBS_H
#define ALIEN_LEXER_STUBS_H

namespace alien::lexer {

    static const char* required_code =
            "#include <iostream>\n"
            "#include <map>\n"
            "#include <stdexcept>\n"
            "#include <string>\n"
            "#include <vector>\n"
            "#include \"utf8proc.h\"\n\n"
            "namespace lexer {\n\n"
            "#define BEGIN(context) const auto& ncontext = context_mapping.find(#context); \\\n"
            "if (ncontext == context_mapping.end()) {                                      \\\n"
            "    throw context_exception(#context);                                        \\\n"
            "}                                                                             \\\n"
            "current_context = ncontext->second;                                           \\\n"
            "current_state = start_states[current_context]\n\n"
            "struct pos {\n"
            "    unsigned int line, column;\n"
            "};\n\n"
            "//generate line:column string\n"
            "std::string gen_lc(pos position) {\n"
            "    return std::to_string(position.line) + ':' + std::to_string(position.column);\n"
            "}\n\n"
            "struct lexeme_too_long_exception : public std::exception {\n"
            "    unsigned int line, column;\n"
            "    std::string description;\n\n"
            "    lexeme_too_long_exception(unsigned int line, unsigned int column) : line(line), column(column) {\n"
            "        description = \"Lexeme too long. \" + gen_lc({line, column});\n"
            "    }\n\n"
            "    const char* what() const noexcept override {\n"
            "        return description.c_str();\n"
            "    }\n"
            "};\n\n"
            "struct context_exception : public std::exception {\n"
            "    std::string description;\n\n"
            "    context_exception(std::string&& context) {\n"
            "        description = \"No such context: \" + context;\n"
            "    }\n\n"
            "    const char* what() const noexcept override {\n"
            "        return description.c_str();\n"
            "    }\n"
            "};\n\n"
            "struct lexing_exception : public std::exception {\n"
            "    unsigned int line, column;\n"
            "    std::string description;\n\n"
            "    lexing_exception(unsigned int line, unsigned int column) : line(line), column(column) {\n"
            "        description = \"Unable to tokenize input. \" + gen_lc({line, column});\n"
            "    }\n\n"
            "    const char* what() const noexcept override {\n"
            "        return description.c_str();\n"
            "    }\n"
            "};\n\n";

    static const char* default_token =
            "template<typename T>\n"
            "struct generalized_token {\n"
            "    static_assert(std::is_enum<T>(), \"Template type must be an enum\");\n\n"
            "    using t = generalized_token<T>;\n\n"
            "    T type;\n\n"
            "    pos start, end;\n\n"
            "    explicit generalized_token(T type, pos start, pos end) : type(type), start(start), end(end) {}\n\n"
            "    virtual ~generalized_token() = default;\n"
            "};\n\n";

    static const char* default_error_function =
            "void error(unsigned int line, unsigned int column) {\n"
            "    throw lexing_exception(line, column);\n"
            "}\n\n";

    static const char* default_eof_action =
            "                    return nullptr;\n";

    static const char* lexer_start =
//            "class lexer {\n"
//            "    char buffer[16386];\n"
//            "    std::istream& stream;\n"
//            "    std::string text;\n\n"
//            "    unsigned int begin = 0, pos = 0, chars_since_las = 0, line = 1, column = 1;\n"
//            "    int las_rule_number = -1;\n"
//            "\n"
//            "    bool stream_end = false, accepted = false;\n"
//            "    struct state {\n"
//            "        std::map<char, unsigned int> transitions;\n"
//            "\n"
//            "        bool accepting;\n"
//            "        int rule_number;\n"
//            "    };\n"
//            "\n"
//            "    unsigned int current_state, current_context = 0;\n\n";
            "class lexer {\n"
            "    utf8proc_uint8_t cbuffer[32771];\n"
            "    utf8proc_int32_t buffer[8193];\n"
            "\n"
            "    std::istream& stream;\n"
            "    std::basic_string<utf8proc_int32_t> text;\n"
            "\n"
            "    unsigned int cpos = 0, cstr_size, cunread = 0, clast_length = 0, bytes_since_las = 0;\n"
            "    unsigned int pos = 0, unread = 0, chars_since_las = 0;\n"
            "    unsigned line = 1, column = 1, las_line = 1, las_column = 1, sline = 1, scolumn = 1;\n"
            "    int las_rule_number = -1;\n"
            "\n"
            "    bool stream_end = false, accepted = false;\n"
            "    struct state {\n"
            "        std::map<utf8proc_int32_t, unsigned int> transitions;\n"
            "\n"
            "        bool accepting;\n"
            "        int rule_number;\n"
            "    };\n"
            "\n"
            "    unsigned int current_state, current_context = 0;\n\n";

    static const char* lexer_constructor_start =
            "public:\n"
            "    explicit lexer(std::istream &stream) : stream(stream), current_state(";

    static const char* lexer_constructor_end =
//            ") {\n"
//            "        fill<0, 8191>();\n"
//            "\n"
//            "        if (dfa[current_context][current_state].accepting) {\n"
//            "            las_rule_number = dfa[current_context][current_state].rule_number;\n"
//            "        }\n"
//            "    }\n\n";

            ") {\n"
            "        fill();\n\n"
            "        if (dfa[current_context][current_state].accepting) {\n"
            "            las_rule_number = dfa[current_context][current_state].rule_number;\n"
            "        }\n"
            "    }\n\n";

    static const char* lex_method_start =
//            "        while (true) {\n"
//            "            if (accepted) {\n"
//            "                begin = pos;\n"
//            "                accepted = false;\n"
//            "            }\n\n"
//            "            char c = buffer[pos++];\n"
//            "\n"
//            "            auto transition = dfa[current_context][current_state].transitions.find(c);\n"
//            "\n"
//            "            if (transition != dfa[current_context][current_state].transitions.end()) {\n"
//            "                if (c != -2) {\n"
//            "                    ++column;\n"
//            "                }\n\n"
//            "                if (c == '\\n') {\n"
//            "                    ++line;\n"
//            "                    column = 1;\n"
//            "                }\n\n"
//            "                ++chars_since_las;\n"
//            "                current_state = transition->second;\n"
//            "\n"
//            "                if (dfa[current_context][current_state].accepting) {\n"
//            "                    las_rule_number = dfa[current_context][current_state].rule_number;\n"
//            "                    chars_since_las = 0;\n"
//            "                }\n"
//            "\n"
//            "                continue;\n"
//            "            }\n"
//            "\n"
//            "            if (c == -2) {\n"
//            "                if (!stream_end) {\n"
//            "                    if (pos == 8193) {\n"
//            "                        fill_second();\n"
//            "\n"
//            "                        continue;\n"
//            "                    }\n"
//            "\n"
//            "                    fill_first();\n"
//            "                    pos = 0;\n"
//            "                    continue;\n"
//            "                } else if (pos - begin == 1) {\n"
//            "                    // eof action\n";

            "        while (true) {\n"
            "            if (accepted) {\n"
            "                for (int i = 0; i < unread; ++i) {\n"
            "                    buffer[i] = buffer[pos - chars_since_las + i];\n"
            "                }\n\n"
            "                chars_since_las = 0;\n"
            "                bytes_since_las = 0;\n"
            "                pos = 0;\n"
            "                accepted = false;\n\n"
            "                sline = line;\n"
            "                scolumn = column;\n"
            "            }\n\n"
            "            utf8proc_int32_t c = next_char();\n\n"
            "            if (move(c) || move(get_class(c))) {\n"
            "                if (unread > 0) {\n"
            "                    --unread;\n"
            "                }\n\n"
            "                if (pos >= sizeof buffer / sizeof(buffer[0])) {\n"
            "                    throw lexeme_too_long_exception(line, column);\n"
            "                }\n\n"
            "                buffer[pos++] = c;\n"
            "                cpos += clast_length;\n"
            "                continue;\n"
            "            }\n\n"
            "            if (c == -2) {\n"
            "                if (!stream_end) {\n"
            "                    fill();\n"
            "                    continue;\n"
            "                } else if (pos == 0) {\n"
            "                    // eof action\n";

    static const char* lex_method_after_eof =
            "                }\n"
            "            }\n\n"
            "            if (las_rule_number == -1) {\n";

    static const char* lex_method_mid =
//            "            }\n\n"
//            "            unsigned int rule_number = las_rule_number;\n"
//            "\n"
//            "            pos = pos - chars_since_las - 1;\n"
//            "            las_rule_number = -1;\n"
//            "            current_state = start_states[current_context];\n"
//            "            accepted = true;\n\n"
//            "            switch (rule_number) {\n";
            "            }\n\n"
            "            unsigned int rule_number = las_rule_number;\n\n"
            "            unread = chars_since_las;\n"
            "            cpos -= bytes_since_las;\n"
            "            las_rule_number = -1;\n"
            "            current_state = start_states[current_context];\n"
            "            accepted = true;\n\n"
            "            line = las_line;\n"
            "            column = las_column;\n\n"
            "            switch (rule_number) {\n";

    static const char* lex_method_end =
            "            }\n"
            "        }\n"
            "    }\n";

    static const char* lexer_end =
//            "\n"
//            "private:\n"
//            "    template<unsigned int start, unsigned int end>\n"
//            "    void fill() {\n"
//            "        static_assert(end > start);\n"
//            "        static_assert(end <= 16384);\n"
//            "        static_assert(start >= 0);\n"
//            "\n"
//            "        int diff = end - start + 1;\n"
//            "\n"
//            "        stream.read(buffer + start, diff);\n"
//            "\n"
//            "        if (stream.eof()) {\n"
//            "            stream_end = true;\n"
//            "\n"
//            "            buffer[start + stream.gcount()] = -2;\n"
//            "        }\n"
//            "\n"
//            "        buffer[start + diff] = -2;\n"
//            "    }\n"
//            "\n"
//            "    void fill_first() {\n"
//            "        if (begin >= 0 && begin <= 8191) {\n"
//            "            throw lexeme_too_long_exception(line, column);\n"
//            "        }\n"
//            "\n"
//            "        fill<0, 8191>();\n"
//            "    }\n"
//            "\n"
//            "    void fill_second() {\n"
//            "        if (begin >= 8193 && begin <= 16384) {\n"
//            "            throw lexeme_too_long_exception(line, column);\n"
//            "        }\n"
//            "\n"
//            "        fill<8193, 16384>();\n"
//            "    }\n\n"
//            "    std::string gettext() {\n"
//            "        if (begin >= 0 && begin <= 8191) {\n"
//            "            if (pos - 1 >= 0 && pos - 1 <= 8191) {\n"
//            "                return {std::begin(buffer) + begin, std::begin(buffer) + pos};\n"
//            "            }\n"
//            "\n"
//            "            std::string text_begin{std::begin(buffer) + begin, std::begin(buffer) + 8192};\n"
//            "            std::string text_end{std::begin(buffer) + 8193, std::begin(buffer) + pos};\n"
//            "\n"
//            "            return text_begin + text_end;\n"
//            "        }\n"
//            "\n"
//            "        if (pos - 1 >= 8193 && pos - 1 <= 16384) {\n"
//            "            return {std::begin(buffer) + begin, std::begin(buffer) + pos};\n"
//            "        }\n"
//            "        \n"
//            "        std::string text_begin{std::begin(buffer) + begin, std::begin(buffer) + 16385};\n"
//            "        std::string text_end{std::begin(buffer), std::begin(buffer) + pos};\n"
//            "        \n"
//            "        return text_begin + text_end;\n"
//            "    }\n"
//            "};";
//            "\nprivate:\n"
//            "    void fill() {\n"
//            "        for (int i = 0; i < cunread; ++i) {\n"
//            "            cbuffer[cunread - i - 1] = cbuffer[sizeof cbuffer - i - 1];\n"
//            "        }\n"
//            "\n"
//            "        if (stream.eof() && cunread == 0) {\n"
//            "            stream_end = true;\n"
//            "            buffer[pos] = -2;\n"
//            "\n"
//            "            return;\n"
//            "        }\n"
//            "\n"
//            "        stream.read((char*) cbuffer + cunread, (int) (sizeof cbuffer - cunread));\n"
//            "        str_size = get_str_size();\n"
//            "\n"
//            "        if (stream.eof()) {\n"
//            "            cunread = 0;\n"
//            "        } else {\n"
//            "            cunread = sizeof cbuffer - str_size;\n"
//            "        }\n"
//            "\n"
//            "        cpos = 0;\n"
//            "    }\n"
//            "\n"
//            "    static bool is_continuation_byte(utf8proc_uint8_t byte) {\n"
//            "        return byte >> 6 == 2;\n"
//            "    }\n"
//            "\n"
//            "    static bool is_ascii_byte(utf8proc_uint8_t byte) {\n"
//            "        return byte >> 7 == 0;\n"
//            "    }\n"
//            "\n"
//            "    unsigned int get_str_size() {\n"
//            "        if (stream.eof()) {\n"
//            "            return cunread + stream.gcount();\n"
//            "        }\n"
//            "\n"
//            "        unsigned int size = sizeof cbuffer - 3;\n"
//            "\n"
//            "        if (is_ascii_byte(cbuffer[size - 1])) {\n"
//            "            return size;\n"
//            "        }\n"
//            "\n"
//            "        while (size < sizeof cbuffer && is_continuation_byte(cbuffer[size])) {\n"
//            "            ++size;\n"
//            "        }\n"
//            "\n"
//            "        return size;\n"
//            "    }\n"
//            "\n"
//            "    utf8proc_int32_t next_char() {\n"
//            "        if (unread > 0) {\n"
//            "            --unread;\n"
//            "            return buffer[pos++];\n"
//            "        }\n"
//            "\n"
//            "        if (cpos == str_size) {\n"
//            "            return -2;\n"
//            "        }\n"
//            "\n"
//            "        int l = utf8proc_iterate(cbuffer + cpos, (utf8proc_ssize_t) str_size, &buffer[pos]);\n"
//            "\n"
//            "        if (l <= 0) {\n"
//            "            throw std::runtime_error(std::string(\"Error occurred while processing the input\") + utf8proc_errmsg(l));\n"
//            "        }\n"
//            "\n"
//            "        cpos += l;\n"
//            "        return buffer[pos++];\n"
//            "    }\n"
//            "};";
            "\nprivate:\n"
            "    bool move(utf8proc_int32_t c) {\n"
            "        auto transition = dfa[current_context][current_state].transitions.find(c);\n"
            "\n"
            "        if (transition != dfa[current_context][current_state].transitions.end()) {\n"
            "            utf8proc_int32_t c_class = get_class(c);\n\n"
            "            if (c_class == -5 || c_class == -31 || c_class == -32) {\n"
            "                ++line;\n"
            "                column = 1;\n"
            "            } else {\n"
            "                ++column;\n"
            "            }\n\n"
            "            ++chars_since_las;\n"
            "            bytes_since_las += clast_length;\n"
            "            current_state = transition->second;\n"
            "\n"
            "            if (dfa[current_context][current_state].accepting) {\n"
            "                las_rule_number = dfa[current_context][current_state].rule_number;\n"
            "                chars_since_las = 0;\n"
            "                bytes_since_las = 0;\n\n"
            "                las_line = line;\n"
            "                las_column = column;\n"
            "            }\n"
            "\n"
            "            return true;\n"
            "        }\n"
            "\n"
            "        return false;\n"
            "    }\n"
            "\n"
            "    static utf8proc_int32_t get_class(utf8proc_int32_t c) {\n"
            "        if (c < 0) {\n"
            "            return c;\n"
            "        }\n"
            "\n"
            "        switch (utf8proc_category(c)) {\n"
            "            case UTF8PROC_CATEGORY_CN:\n"
            "                throw std::invalid_argument(\"Codepoint must be assigned\");\n"
            "            case UTF8PROC_CATEGORY_LU:\n"
            "                return -12;\n"
            "            case UTF8PROC_CATEGORY_LL:\n"
            "                return -8;\n"
            "            case UTF8PROC_CATEGORY_LT:\n"
            "                return -11;\n"
            "            case UTF8PROC_CATEGORY_LM:\n"
            "                return -9;\n"
            "            case UTF8PROC_CATEGORY_LO:\n"
            "                return -10;\n"
            "            case UTF8PROC_CATEGORY_MN:\n"
            "                return -15;\n"
            "            case UTF8PROC_CATEGORY_MC:\n"
            "                return -13;\n"
            "            case UTF8PROC_CATEGORY_ME:\n"
            "                return -14;\n"
            "            case UTF8PROC_CATEGORY_ND:\n"
            "                return -16;\n"
            "            case UTF8PROC_CATEGORY_NL:\n"
            "                return -17;\n"
            "            case UTF8PROC_CATEGORY_NO:\n"
            "                return -18;\n"
            "            case UTF8PROC_CATEGORY_PC:\n"
            "                if (c == '_') {\n"
            "                    return -20;\n"
            "                }\n"
            "\n"
            "                return -19;\n"
            "            case UTF8PROC_CATEGORY_PD:\n"
            "                return -21;\n"
            "            case UTF8PROC_CATEGORY_PS:\n"
            "                return -26;\n"
            "            case UTF8PROC_CATEGORY_PE:\n"
            "                return -22;\n"
            "            case UTF8PROC_CATEGORY_PI:\n"
            "                return -24;\n"
            "            case UTF8PROC_CATEGORY_PF:\n"
            "                return -23;\n"
            "            case UTF8PROC_CATEGORY_PO:\n"
            "                return -25;\n"
            "            case UTF8PROC_CATEGORY_SM:\n"
            "                return -29;\n"
            "            case UTF8PROC_CATEGORY_SC:\n"
            "                return -27;\n"
            "            case UTF8PROC_CATEGORY_SK:\n"
            "                return -28;\n"
            "            case UTF8PROC_CATEGORY_SO:\n"
            "                return -30;\n"
            "            case UTF8PROC_CATEGORY_ZS:\n"
            "                return -33;\n"
            "            case UTF8PROC_CATEGORY_ZL:\n"
            "                return -31;\n"
            "            case UTF8PROC_CATEGORY_ZP:\n"
            "                return -32;\n"
            "            case UTF8PROC_CATEGORY_CC:\n"
            "                if (c == '\\t') {\n"
            "                    return -4;\n"
            "                }\n"
            "\n"
            "                if (c == '\\n' || c == '\\v' || c == '\\f' || c == '\\r' || c == 133) { // 133 - u+85, NEL\n"
            "                    return -5;\n"
            "                }\n"
            "\n"
            "                return -3;\n"
            "            case UTF8PROC_CATEGORY_CF:\n"
            "                if (c == 6158) { // 6158 - u+180e, Mongolian Vowel Separator (MVS)\n"
            "                    return -7;\n"
            "                }\n"
            "\n"
            "                return -6;\n"
            "            case UTF8PROC_CATEGORY_CS:\n"
            "            case UTF8PROC_CATEGORY_CO:\n"
            "                throw std::invalid_argument(\"Invalid character category\");\n"
            "        }\n"
            "    }\n"
            "\n"
            "\n"
            "    void fill() {\n"
            "        for (int i = 0; i < cunread; ++i) {\n"
            "            cbuffer[i] = cbuffer[sizeof cbuffer - cunread + i];\n"
            "        }\n"
            "\n"
            "        if (stream.eof() && cunread == 0) {\n"
            "            stream_end = true;\n"
            "            buffer[pos] = -2;\n"
            "\n"
            "            return;\n"
            "        }\n"
            "\n"
            "        stream.read((char*) cbuffer + cunread, (int) (sizeof cbuffer - cunread));\n"
            "        cstr_size = get_str_size();\n"
            "\n"
            "        if (stream.eof()) {\n"
            "            cunread = 0;\n"
            "        } else {\n"
            "            cunread = sizeof cbuffer - cstr_size;\n"
            "        }\n"
            "\n"
            "        cpos = 0;\n"
            "    }\n"
            "\n"
            "    static bool is_continuation_byte(utf8proc_uint8_t byte) {\n"
            "        return byte >> 6 == 2;\n"
            "    }\n"
            "\n"
            "    static bool is_ascii_byte(utf8proc_uint8_t byte) {\n"
            "        return byte >> 7 == 0;\n"
            "    }\n"
            "\n"
            "    unsigned int get_str_size() {\n"
            "        if (stream.eof()) {\n"
            "            return cunread + stream.gcount();\n"
            "        }\n"
            "\n"
            "        unsigned int size = sizeof cbuffer - 3;\n"
            "\n"
            "        if (is_ascii_byte(cbuffer[size - 1])) {\n"
            "            return size;\n"
            "        }\n"
            "\n"
            "        while (size < sizeof cbuffer && is_continuation_byte(cbuffer[size])) {\n"
            "            ++size;\n"
            "        }\n"
            "\n"
            "        return size;\n"
            "    }\n"
            "\n"
            "    utf8proc_int32_t next_char() {\n"
            "        if (unread > 0) {\n"
            "            return buffer[pos];\n"
            "        }\n"
            "\n"
            "        if (cpos == cstr_size) {\n"
            "            return -2;\n"
            "        }\n"
            "\n"
            "        utf8proc_int32_t c;\n"
            "        int l = utf8proc_iterate(cbuffer + cpos, (utf8proc_ssize_t) cstr_size, &c);\n"
            "\n"
            "        if (l <= 0) {\n"
            "            throw std::runtime_error(std::string(\"Error occurred while processing the input \") + utf8proc_errmsg(l));\n"
            "        }\n"
            "\n"
            "        clast_length = l;\n"
            "        return c;\n"
            "    }\n"
            "    std::basic_string<utf8proc_int32_t> gettext() {\n"
            "        return {std::begin(buffer), std::begin(buffer) + pos};\n"
            "    }\n"
            "};\n\n"
            "}";
}

#endif //ALIEN_LEXER_STUBS_H